[[main]]
name = "sobre"
identifier = "about"
weight = 1
[main.params]
section = "about"
idx = "01"

[[main]]
name = "stack"
identifier = "stack"
weight = 2
[main.params]
section = "stack"
idx = "02"

[[main]]
name = "experiência"
identifier = "experience"
weight = 3
[main.params]
section = "experience"
idx = "03"

[[main]]
name = "projetos"
identifier = "project"
weight = 4
[main.params]
section = "project"
idx = "04"

[[main]]
name = "contacto"
identifier = "contact"
weight = 5
[main.params]
section = "contact"
idx = "05"

[[main]]
name = "blog"
identifier = "blog"
weight = 6
[main.params]
url = "/blog/"
idx = "06"
