[[main]]
name = "proyectos"
identifier = "project"
weight = 1
[main.params]
section = "project"
idx = "01"

[[main]]
name = "blog"
identifier = "blog"
weight = 2
[main.params]
url = "/blog/"
idx = "02"

[[main]]
name = "servicios"
identifier = "work"
weight = 3
[main.params]
section = "work"
idx = "03"

[[main]]
name = "contacto"
identifier = "contact"
weight = 4
[main.params]
section = "contact"
idx = "04"

[[main]]
name = "cv"
identifier = "cv"
weight = 5
[main.params]
url = "/cv/"
idx = "05"
